title:              Felipe Mota
email:              felipemotacontato@gmail.com
description:        Felipe Mota Website
author:             Felipe Mota
baseurl:            ""
url:                "https://blackrockdigital.github.io"

# Header
header-color:       ff0094
header_title: I’m Felipe Mota, I create things for the web.
header_description: I'm a frontend-developer specializing in building analytics products.

# Social Profiles
twitter_username:   felipemotabr
github_username:    felipemotabr
facebook_username:  
linkedin_username:  felipemotabr
behance_username:   felipemotabr

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

collections:
  works:
    title: Works
    output: true
    permalink: /work/:name/

# Multiple Languages  
languages: ["pt", "en"]

exclude_from_localizations: ["assets"]

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-multiple-languages-plugin
